aws_region        = "us-east-1"
environment       = "preprod"
namespace         = "frontend"
helm_release_name = "frontend"
helm_chart_path   = "../helm"
helm_values_file  = "../helm/values-preprod.yaml"