namespace: frontend

replicaCount: 2

image:
  repository: 942548380129.dkr.ecr.us-east-1.amazonaws.com/roboshop/frontend
  tag: "1.0.0"
  digest: ""
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  host: dev.optimusprime.uno
  path: /
  pathType: Prefix
  certificateArn: arn:aws:acm:us-east-1:942548380129:certificate/04035cfa-147e-46be-aca6-93361d8a3c0b